/**
 * SoberAF Sticker Studio - Delete Design Lambda
 *
 * Deletes a design and every artifact associated with it:
 *   - the raw S3 object generated by DALL-E
 *   - every processed size (small / medium / large) in the processed bucket
 *   - the DynamoDB metadata row
 *
 * Triggered by API Gateway: DELETE /designs/{designId}
 *
 * Returns 200 even if some artifacts were already missing — the operation
 * is idempotent, so calling it twice on the same designId is safe.
 */

import { S3Client, DeleteObjectCommand, ListObjectsV2Command } from '@aws-sdk/client-s3';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand, DeleteCommand } from '@aws-sdk/lib-dynamodb';

const s3 = new S3Client();
const dynamoClient = new DynamoDBClient();
const dynamo = DynamoDBDocumentClient.from(dynamoClient);

export const handler = async (event) => {
  console.log('Delete Lambda invoked:', JSON.stringify(event));

  try {
    // Extract designId from path parameters.
    const designId = event.pathParameters && event.pathParameters.designId;
    if (!designId) {
      return buildResponse(400, { error: 'designId is required in the path' });
    }

    console.log('Deleting design:', designId);

    // Look up the metadata row so we know exactly which keys to delete.
    // If it doesn't exist, we still attempt the delete-by-prefix below
    // because the row may have been removed earlier.
    let item = null;
    try {
      const result = await dynamo.send(new GetCommand({
        TableName: process.env.METADATA_TABLE,
        Key: { designId: designId },
      }));
      item = result.Item || null;
    } catch (err) {
      console.warn('GetCommand failed (continuing):', err.message);
    }

    // Delete the raw image. We try the explicit key from metadata first,
    // and then sweep the entire prefix to catch anything else under it.
    if (item && item.rawKey) {
      await safeDelete(process.env.RAW_BUCKET, item.rawKey);
    }
    await deleteByPrefix(process.env.RAW_BUCKET, `${designId}/`);

    // Delete every processed size. Same pattern: explicit keys from
    // metadata first, then a prefix sweep as belt-and-suspenders.
    if (item && item.processedKeys) {
      for (const key of Object.values(item.processedKeys)) {
        await safeDelete(process.env.PROCESSED_BUCKET, key);
      }
    }
    await deleteByPrefix(process.env.PROCESSED_BUCKET, `${designId}/`);

    // Finally, delete the DynamoDB row itself.
    await dynamo.send(new DeleteCommand({
      TableName: process.env.METADATA_TABLE,
      Key: { designId: designId },
    }));

    console.log('Design deleted successfully:', designId);

    return buildResponse(200, {
      message: 'Design deleted',
      designId: designId,
    });

  } catch (error) {
    console.error('Error in delete function:', error);
    return buildResponse(500, {
      error: 'Failed to delete design',
      details: error.message,
    });
  }
};

/**
 * Deletes a single S3 object, swallowing NoSuchKey errors so callers can
 * use this idempotently.
 */
async function safeDelete(bucket, key) {
  try {
    await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: key }));
    console.log(`Deleted s3://${bucket}/${key}`);
  } catch (err) {
    if (err.name === 'NoSuchKey' || err.Code === 'NoSuchKey') {
      console.log(`Already gone: s3://${bucket}/${key}`);
      return;
    }
    console.warn(`Failed to delete s3://${bucket}/${key}:`, err.message);
  }
}

/**
 * Lists every object under a given prefix and deletes each one. Useful for
 * cleaning up any artifacts whose keys aren't recorded in the metadata row,
 * which can happen if processing was interrupted partway through.
 */
async function deleteByPrefix(bucket, prefix) {
  let continuationToken = undefined;

  do {
    const listResult = await s3.send(new ListObjectsV2Command({
      Bucket: bucket,
      Prefix: prefix,
      ContinuationToken: continuationToken,
    }));

    const objects = listResult.Contents || [];
    for (const obj of objects) {
      await safeDelete(bucket, obj.Key);
    }

    continuationToken = listResult.IsTruncated ? listResult.NextContinuationToken : undefined;
  } while (continuationToken);
}

/**
 * Builds a CORS-friendly API Gateway response.
 */
function buildResponse(statusCode, body) {
  return {
    statusCode: statusCode,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
    body: JSON.stringify(body),
  };
}
